apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmk8
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mmk8
  template:
    metadata:
      labels:
        app: mmk8
    spec:
      containers:
      - name: mmk8
        image: ghcr.io/ridomin/pnp-memmon-hub:dps1
        