apiVersion: apps/v1
kind: Deployment
metadata:
  name: mm-hive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mm-hive
  template:
    metadata:
      labels:
        app: mm-hive
    spec:
      containers:
      - name: mm-hive
        image: ghcr.io/ridomin/pnp-memmon-hive:latest
        env:
        - name: ConnectionStrings__cs
          value: HostName=f8826e3352314ca98102cfbde8aff20e.s2.eu.hivemq.cloud;UserName=demo1;Password=MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA1;ClientId=mm-hive
      dnsPolicy: Default
        