apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotux-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iothubux
  template:
    metadata:
      labels:
        app: iothubux
    spec:
      containers:
      - name: iothubux
        image: ghcr.io/ridomin/iotux:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__hub
          value: "HostName=rido.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=7Fnf/DRygqQ6WxK77+5pIev5McFkfQfE53m2Oxav4Yk="
---
apiVersion: v1
kind: Service
metadata:
  name: iothubux-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: iothubux