apiVersion: apps/v1
kind: Deployment
metadata:
  name: aznorthbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aznorthbound
  template:
    metadata:
      labels:
        app: aznorthbound
    spec:
      containers:
      - name: aznorthbound
        image: ghcr.io/ridomin/ridoaznorthbound:latest
        env:
        - name: ConnectionStrings__cs
          value: HostName=10.0.50.186;UserName=a;Password=b;ClientId=NorthBoundConnector;TcpPort=1883;UseTls=false
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: InstrumentationKey=065bcb1a-bf6d-43c8-b541-e374a92b082a;IngestionEndpoint=https://westus3-1.in.applicationinsights.azure.com/
      hostNetwork: false
      dnsPolicy: Default
        