apiVersion: apps/v1
kind: Deployment
metadata:
  name: aznorthbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aznorthbound
  template:
    metadata:
      labels:
        app: aznorthbound
    spec:
      containers:
      - name: aznorthbound
        image: ghcr.io/ridomin/ridoaznorthbound:latest
        env:
        - name: ConnectionStrings__cs
          value: HostName=mosquitto-service;ClientId=NorthBoundConnector;TcpPort=1883;UseTls=false
        - name: ConnectionStrings__eh
          value: Endpoint=sb://iotconnectors.servicebus.windows.net/;SharedAccessKeyName=PreviewDataPolicy;SharedAccessKey=f7w1mhTYF4icfOY7gndE0E6uUM1JAsr2WcSVyaA27ZE=;EntityPath=frommosquitto
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: InstrumentationKey=065bcb1a-bf6d-43c8-b541-e374a92b082a;IngestionEndpoint=https://westus3-1.in.applicationinsights.azure.com/