apiVersion: apps/v1
kind: Deployment
metadata:
  name: e4k-device
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e4k-device
  template:
    metadata:
      labels:
        app: e4k-device
    spec:
      containers:
      - name: e4k-device
        image: ghcr.io/iotmodels/memmon:e4k
        env:
        - name: ConnectionStrings__cs
          value: HostName=azedge-dmqtt-frontend;TcpPort=1883;UseTls=false;Username=client1;Password=password