apiVersion: apps/v1
kind: Deployment
metadata:
  name: e4k-device
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e4k-device
  template:
    metadata:
      labels:
        app: e4k-device
    spec:
      containers:
      - name: e4k-device
        image: ghcr.io/ridomin/pnp-memmon-hive:latest
        env:
        - name: ConnectionStrings__cs
          value: HostName=mqttbroker-svc;TcpPort=1883;UseTls=false