apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotux
  namespace: webs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotux
  template:
    metadata:
      labels:
        app: iotux
    spec:
      containers:
      - name: iotux
        image: ghcr.io/iotmodels/iotux:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: ConnectionStrings__hub
          value: "HostName=rido.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=7Fnf/DRygqQ6WxK77+5pIev5McFkfQfE53m2Oxav4Yk="
        
---
apiVersion: v1
kind: Service
metadata:
  name: iotux
  namespace: webs
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: iotux
