apiVersion: apps/v1
kind: Deployment
metadata:
  name: mm-central
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mm-central
  template:
    metadata:
      labels:
        app: mm-central
    spec:
      containers:
      - name: mm-central
        image: ghcr.io/iotmodels/memmon:x64
        imagePullPolicy: Always
        env:
        - name: ConnectionStrings__cs
          value: IdScope=0ne006CAFFC;SharedAccessKey=invalid
        - name: masterKey
          value: vyB2VqViNdAILXTw5SRiKNiSrrfgPLOy9/sDu2d2ZaP/NSD3Y/0NNrnJ2O7S6wjdxLTCYTIpb3kNsHpipts7ew==

        