apiVersion: apps/v1
kind: Deployment
metadata:
  name: mm-dpshub
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mm-dpshub
  template:
    metadata:
      labels:
        app: mm-dpshub
    spec:
      containers:
      - name: mm-dpshub
        image: ghcr.io/iotmodels/memmon:x64
        imagePullPolicy: Always
        env:
        - name: ConnectionStrings__cs
          value: IdScope=0ne00890689
        - name: masterKey
          value: 9cJ1WVYTGHGl66hpUTuBE7+rRO9bCRBWQizbunttuRYN22tmoeQsPudFPTlVokFJ1pyTh0xGXeo2Gevsv3pG2Q==
      
        