apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  mosquitto.conf: |-
    per_listener_settings true

    listener 1883
    allow_anonymous false
    password_file /mosquitto/secrets/passwords.txt

    listener 8883
    allow_anonymous false
    password_file /mosquitto/secrets/passwords.txt
    cafile /mosquitto/secrets/ca.crt
    certfile /mosquitto/secrets/tls.crt
    keyfile /mosquitto/secrets/tls.key
    tls_version tlsv1.2

    listener 8884
    require_certificate true
    use_identity_as_username true
    cafile /mosquitto/secrets/ca2.crt
    certfile /mosquitto/secrets/tls2.crt
    keyfile /mosquitto/secrets/tls2.key
    tls_version tlsv1.2

    listener 8880
    allow_anonymous false
    password_file /mosquitto/secrets/passwords.txt
    protocol websockets

    listener 8443
    allow_anonymous false
    password_file /mosquitto/secrets/passwords.txt
    protocol websockets
    cafile /mosquitto/secrets/ca.crt
    certfile /mosquitto/secrets/tls.crt
    keyfile /mosquitto/secrets/tls.key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mosquitto
  template:
    metadata:
      labels:
        name: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
          - containerPort: 1883
          - containerPort: 8883
          - containerPort: 8884
          - containerPort: 8880
          - containerPort: 8443
          volumeMounts:
          - name: mosquitto-conf
            mountPath: /mosquitto/config
          - name: mosquitto-tls
            mountPath: /mosquitto/secrets
      volumes:
      - name: mosquitto-conf
        configMap:
          name: mosquitto-config-file
      - name: mosquitto-tls
        secret:
          secretName: mosquitto-certs
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  type: LoadBalancer # <-- Changed
  selector:
    name: mosquitto
  ports:
    - name: mosquitto-tcp
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mosquitto-tls
      protocol: TCP
      port: 8883
      targetPort: 8883
    - name: mosquitto-tls-cc
      protocol: TCP
      port: 8884
      targetPort: 8884
    - name: mosquitto-ws
      protocol: TCP
      port: 8880
      targetPort: 8880
    - name: mosquitto-wss
      protocol: TCP
      port: 8443
      targetPort: 8443
