apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  mosquitto.conf: |-
    listener 1883
    allow_anonymous true

    listener 8883
    cafile /mosquitto/certs/tls.crt
    certfile /mosquitto/certs/tls.crt
    keyfile /mosquitto/certs/tls.key
    tls_version tlsv1.2

    listener 8884
    protocol websockets
    cafile /mosquitto/certs/tls.crt
    certfile /mosquitto/certs/tls.crt
    keyfile /mosquitto/certs/tls.key
    tls_version tlsv1.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mosquitto
  template:
    metadata:
      labels:
        name: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
          - containerPort: 1883
          - containerPort: 8883
          - containerPort: 8884
          volumeMounts:
          - name: mosquitto-conf
            mountPath: /mosquitto/config
          - name: mosquitto-tls
            mountPath: /mosquitto/certs
      volumes:
      - name: mosquitto-conf
        configMap:
          name: mosquitto-config-file
      - name: mosquitto-tls
        secret:
          secretName: mosquitto-certs
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  type: LoadBalancer # <-- Changed
  selector:
    name: mosquitto
  ports:
    - name: mosquitto-tcp
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mosquitto-tls
      protocol: TCP
      port: 8883
      targetPort: 8883
    - name: mosquitto-wss
      protocol: TCP
      port: 8884
      targetPort: 8884
