apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosq-device
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mosq-device
  template:
    metadata:
      labels:
        app: mosq-device
    spec:
      containers:
      - name: mosq-device
        image: ghcr.io/ridomin/memmon:latest
        env:
        - name: ConnectionStrings__cs
          value: HostName=mosquitto-service;TcpPort=1883;UseTls=false