apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosq-device
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mosq-device
  template:
    metadata:
      labels:
        app: mosq-device
    spec:
      containers:
      - name: mosq-device
        image: ghcr.io/iotmodels/memmon:x64
        env:
        - name: ConnectionStrings__cs
          value: HostName=mosquitto-service;TcpPort=1883;UseTls=false;UserName=client2;Password=Pass@Word2;clientId={machineName}