apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-grpc
  template:
    metadata:
      labels:
        app: mqtt-grpc
    spec:
      containers:
      - name: mqtt-grpc
        image: ghcr.io/iotmodels/mqtt-grpc-device:latest
        imagePullPolicy: Always
        env:
        - name: ConnectionStrings__cs
          value: HostName=mosquitto.rido.dev;TcpPort=8884;X509Key=certs/tls.crt|certs/tls.key;CaFile=ca.pem
        volumeMounts:
          - name: my-device-x509
            mountPath: /app/certs
      volumes:
      - name: my-device-x509
        secret: 
          secretName: mqtt-grpc-device
      
        