apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-broker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pi-broker
  template:
    metadata:
      labels:
        app: pi-broker
    spec:
      containers:
      - name: pi-broker
        image: ghcr.io/iotmodels/pi-sense-device:x64
        imagePullPolicy: Always
        env:
        - name: ConnectionStrings__cs
          value: HostName=mosquitto-service;TcpPort=1883;UseTls=false;Username=client2;Password=Pass@Word2;ClientId={machineName}
        - name: ApplicationInsights__ConnectionString
          value: InstrumentationKey=216d32bc-3c75-41d2-8c5d-7fc55958fe9b;IngestionEndpoint=https://westus-0.in.applicationinsights.azure.com/;LiveEndpoint=https://westus.livediagnostics.monitor.azure.com/

        