e4kdmqtt:
  broker:
    frontend:
      ports:
      - port: 1883
      - port: 8883
        tls:
          secret: e4k-tls-cert

  authenticationMethods:
    - method: x509
    - method: username-password
      password_database: credentials
