name: memmon Docker Image CI

on:
  push:
    branches: [ "master", "dev" ]
    tags: ['v.*']
    paths:
      - 'memmon/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file memmon/Dockerfile --tag ghcr.io/ridomin/memmon:x64
    - name: push image
      run: docker push ghcr.io/ridomin/memmon:x64
    - name: Build the Docker image ARM
      run: docker build . --file memmon/Dockerfile.pi --tag ghcr.io/ridomin/memmon:arm
    - name: push image arm
      run: docker push ghcr.io/ridomin/memmon:arm
