name: mm hive Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths: 
      - 'pnp-memmon-broker/**'
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file pnp-memmon-broker/Dockerfile --tag ghcr.io/ridomin/pnp-memmon-broker:latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: push image
      run: docker push ghcr.io/ridomin/pnp-memmon-broker:latest
